/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectofinal.vistas;

import javax.swing.JOptionPane;
import proyectofinal.Entidades.Libro;
import proyectofinal.accesoDatos.LibroData;

/**
 *
 * @author Usuario
 */
public class gestorLibros extends javax.swing.JInternalFrame {
private LibroData ld = new LibroData();
    /**
     * Creates new form gestorPrestamos
     */
    public gestorLibros() {
        initComponents();
        inicializarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tIsbn = new javax.swing.JTextField();
        tTitulo = new javax.swing.JTextField();
        tAnio = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        tAutor = new javax.swing.JTextField();
        tEditorial = new javax.swing.JTextField();
        rbEstado = new javax.swing.JRadioButton();
        bGuardar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bNuevo = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel1.setText("Gestor de libros");

        jLabel2.setText("Título:");

        jLabel3.setText("Año:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("Autor:");

        jLabel6.setText("Editorial:");

        jLabel7.setText("Estado:");

        jLabel8.setText("ISBN:");

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");

        bNuevo.setText("Nuevo");

        bBuscar.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tAutor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tTitulo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbEstado)
                                    .addComponent(tEditorial)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(bNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(bModificar)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bGuardar)
                    .addComponent(bBuscar))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbEstado)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bModificar)
                    .addComponent(bEliminar)
                    .addComponent(bNuevo))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        Long isbn = null;
        String titulo = null;
        Integer anio = null;
        String tipo = null;
        String editorial = null;
        Boolean estado = null;
        String autor = null;
        try {
            isbn = Long.parseLong(tIsbn.getText());
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Solo puede ingresar números enteros en este campo.");
        }

        try {
            titulo = tTitulo.getText();

        } catch (NullPointerException nf) {
            JOptionPane.showMessageDialog(this, "Error al guardar el título");
        }

        try {
            anio = Integer.parseInt(tAnio.getText());

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Solo puede ingresar números enteros en este campo.");
        }

        try {
            tipo = cbTipo.getItemAt(cbTipo.getSelectedIndex());

        } catch (NullPointerException nf) {
            JOptionPane.showMessageDialog(this, "Error al guardar el tipo.");
        }

        try {
            editorial = tEditorial.getText();

        } catch (NullPointerException nf) {
            JOptionPane.showMessageDialog(this, "error al guardar la editorial.");
        }

        try {
            estado = rbEstado.isEnabled();

        } catch (NullPointerException nf) {
            JOptionPane.showMessageDialog(this, "Error al guardar el estado.");
        }

        try {

            autor = tAutor.getText();
        } catch (NullPointerException nf) {
            JOptionPane.showMessageDialog(this, "Error al guardar el autor.");
        }

        try {
            Libro libro = new Libro(isbn, titulo, anio, tipo, editorial, estado, autor);
            ld.guardarLibro(libro);

        } catch (NullPointerException np) {
            JOptionPane.showMessageDialog(this, "No se ha podido guardar el libro, reinténtelo nuevamente.");
        }

    }//GEN-LAST:event_bGuardarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        Long isbn = null;
        String titulo = null;
        Integer anio = null;
        String tipo = null;
        String editorial = null;
        Boolean estado = null;
        String autor = null;
        try {
            isbn = Long.parseLong(tIsbn.getText());
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Solo puede ingresar números enteros en este campo.");
        }

        try {
            titulo = tTitulo.getText();

        } catch (NullPointerException nf) {
            JOptionPane.showMessageDialog(this, "Error al modificar el título");
        }

        try {
            anio = Integer.parseInt(tAnio.getText());

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Solo puede ingresar números enteros en este campo.");
        }

        try {
            tipo = cbTipo.getItemAt(cbTipo.getSelectedIndex());

        } catch (NullPointerException nf) {
            JOptionPane.showMessageDialog(this, "Error al modificar el tipo.");
        }

        try {
            editorial = tEditorial.getText();

        } catch (NullPointerException nf) {
            JOptionPane.showMessageDialog(this, "error al modificar la editorial.");
        }

        try {
            estado = rbEstado.isSelected();
            
        } catch (NullPointerException nf) {
            JOptionPane.showMessageDialog(this, "Error al modificar el estado.");
        }

        try {

            autor = tAutor.getText();
        } catch (NullPointerException nf) {
            JOptionPane.showMessageDialog(this, "Error al modificar el autor.");
        }
        
         try {
            Libro libro = new Libro(isbn, titulo, anio, tipo, editorial, estado, autor);
            ld.modificarLibro(libro);

        } catch (NullPointerException np) {
            JOptionPane.showMessageDialog(this, "No se ha podido modificar el libro, reinténtelo nuevamente.");
        }
    }//GEN-LAST:event_bModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rbEstado;
    private javax.swing.JTextField tAnio;
    private javax.swing.JTextField tAutor;
    private javax.swing.JTextField tEditorial;
    private javax.swing.JTextField tIsbn;
    private javax.swing.JTextField tTitulo;
    // End of variables declaration//GEN-END:variables

    public void inicializarComboBox() {
        cbTipo.addItem("Acción");
        cbTipo.addItem("Aventura");
        cbTipo.addItem("Fantasía");
        cbTipo.addItem("Horror");
        cbTipo.addItem("Ciencia ficción");
        cbTipo.addItem("Sci-fi");
        cbTipo.addItem("Comedia");
        cbTipo.addItem("Drama");
        cbTipo.addItem("Educativo");
        cbTipo.addItem("Informativo");
        cbTipo.addItem("Terror");
        cbTipo.addItem("Thriller");
        cbTipo.addItem("Infantil");

    }
}
