/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal.vistas;

import com.formdev.flatlaf.intellijthemes.FlatGradiantoDeepOceanIJTheme;
import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.border.Border;
import javax.swing.border.MatteBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Usuario
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    public vistaPrincipal() {
        initComponents();
        this.setSize(1025, 708);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Gestion de Biblioteca");
        this.setResizable(false);
        
        
        
    }

    private void inicializarJInternalFrame(JInternalFrame internalFrame, String Titulo) {
    escritorio.removeAll();
    escritorio.setLayout(null);
    escritorio.setBorder(null);
    Border bordes = new MatteBorder(2, 2, 2, 2, Color.BLACK);

    BasicInternalFrameUI ui = (BasicInternalFrameUI) internalFrame.getUI();
    ui.setNorthPane(null);
    internalFrame.setBorder(bordes);
    
    internalFrame.setSize(820, 620);
    internalFrame.setVisible(true);
    
    int x = (escritorio.getWidth() - internalFrame.getWidth()) / 2;
    int y = (escritorio.getHeight() - internalFrame.getHeight()) / 2;
    
    internalFrame.setBounds(x, y, internalFrame.getWidth(), internalFrame.getHeight());

    escritorio.add(internalFrame);
}






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jpMenuSuperior = new javax.swing.JPanel();
        jpMenuItemS1 = new javax.swing.JPanel();
        jlConsultas1 = new javax.swing.JLabel();
        jpMenuItemS2 = new javax.swing.JPanel();
        jlConsultas6 = new javax.swing.JLabel();
        jpMenuItemS3 = new javax.swing.JPanel();
        jlConsultas7 = new javax.swing.JLabel();
        jpMenuItemS4 = new javax.swing.JPanel();
        jlConsultas8 = new javax.swing.JLabel();
        jpMenuItemS5 = new javax.swing.JPanel();
        jlConsultas9 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jpLateral = new javax.swing.JPanel();
        jpLogo1 = new javax.swing.JPanel();
        jpMenuLateral = new javax.swing.JPanel();
        jpMenuItemL1 = new javax.swing.JPanel();
        jlGestorUsuarios = new javax.swing.JLabel();
        jpMenuItemL2 = new javax.swing.JPanel();
        jlGestorLibros = new javax.swing.JLabel();
        jpMenuItemL3 = new javax.swing.JPanel();
        jlGestorEjemplares = new javax.swing.JLabel();
        jpMenuItemL4 = new javax.swing.JPanel();
        jlGestorPrestamos = new javax.swing.JLabel();
        jpLogo = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpFondo.setBackground(new java.awt.Color(23, 28, 46));

        jpMenuSuperior.setBackground(new java.awt.Color(23, 28, 46));

        jpMenuItemS1.setBackground(new java.awt.Color(79, 125, 173));
        jpMenuItemS1.setPreferredSize(new java.awt.Dimension(188, 55));

        jlConsultas1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlConsultas1.setForeground(new java.awt.Color(193, 193, 193));
        jlConsultas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Recursos/img/cEjemplaresDeUnLibro.png"))); // NOI18N
        jlConsultas1.setText("<html>Cantidad de ejemplares de un libro</html>");
        jlConsultas1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlConsultas1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlConsultas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlConsultas1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemS1Layout = new javax.swing.GroupLayout(jpMenuItemS1);
        jpMenuItemS1.setLayout(jpMenuItemS1Layout);
        jpMenuItemS1Layout.setHorizontalGroup(
            jpMenuItemS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlConsultas1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpMenuItemS1Layout.setVerticalGroup(
            jpMenuItemS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuItemS1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlConsultas1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpMenuItemS2.setBackground(new java.awt.Color(79, 125, 173));
        jpMenuItemS2.setPreferredSize(new java.awt.Dimension(188, 55));

        jlConsultas6.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlConsultas6.setForeground(new java.awt.Color(193, 193, 193));
        jlConsultas6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Recursos/img/cPrestamosVencidos.png"))); // NOI18N
        jlConsultas6.setText("<html>Lectores con prestamos vencidos</html>");
        jlConsultas6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlConsultas6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlConsultas6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlConsultas6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemS2Layout = new javax.swing.GroupLayout(jpMenuItemS2);
        jpMenuItemS2.setLayout(jpMenuItemS2Layout);
        jpMenuItemS2Layout.setHorizontalGroup(
            jpMenuItemS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlConsultas6, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );
        jpMenuItemS2Layout.setVerticalGroup(
            jpMenuItemS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlConsultas6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpMenuItemS3.setBackground(new java.awt.Color(79, 125, 173));
        jpMenuItemS3.setPreferredSize(new java.awt.Dimension(188, 55));

        jlConsultas7.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlConsultas7.setForeground(new java.awt.Color(193, 193, 193));
        jlConsultas7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Recursos/img/cLibrosxAutor.png"))); // NOI18N
        jlConsultas7.setText("<html>Libros de un autor específico</html>");
        jlConsultas7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlConsultas7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlConsultas7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlConsultas7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemS3Layout = new javax.swing.GroupLayout(jpMenuItemS3);
        jpMenuItemS3.setLayout(jpMenuItemS3Layout);
        jpMenuItemS3Layout.setHorizontalGroup(
            jpMenuItemS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlConsultas7, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );
        jpMenuItemS3Layout.setVerticalGroup(
            jpMenuItemS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlConsultas7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpMenuItemS4.setBackground(new java.awt.Color(79, 125, 173));
        jpMenuItemS4.setPreferredSize(new java.awt.Dimension(188, 55));

        jlConsultas8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlConsultas8.setForeground(new java.awt.Color(193, 193, 193));
        jlConsultas8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Recursos/img/cLectoresYLibrosdePrestamos.png"))); // NOI18N
        jlConsultas8.setText("<html>Lectores y libros de todos los prestamos</html>");
        jlConsultas8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlConsultas8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlConsultas8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlConsultas8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemS4Layout = new javax.swing.GroupLayout(jpMenuItemS4);
        jpMenuItemS4.setLayout(jpMenuItemS4Layout);
        jpMenuItemS4Layout.setHorizontalGroup(
            jpMenuItemS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlConsultas8, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );
        jpMenuItemS4Layout.setVerticalGroup(
            jpMenuItemS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlConsultas8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpMenuItemS5.setBackground(new java.awt.Color(79, 125, 173));
        jpMenuItemS5.setPreferredSize(new java.awt.Dimension(188, 55));

        jlConsultas9.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlConsultas9.setForeground(new java.awt.Color(193, 193, 193));
        jlConsultas9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Recursos/img/cPrestadosxFecha.png"))); // NOI18N
        jlConsultas9.setText("<html>Libros prestados por fecha</html>");
        jlConsultas9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlConsultas9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlConsultas9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlConsultas9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemS5Layout = new javax.swing.GroupLayout(jpMenuItemS5);
        jpMenuItemS5.setLayout(jpMenuItemS5Layout);
        jpMenuItemS5Layout.setHorizontalGroup(
            jpMenuItemS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlConsultas9, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );
        jpMenuItemS5Layout.setVerticalGroup(
            jpMenuItemS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlConsultas9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpMenuSuperiorLayout = new javax.swing.GroupLayout(jpMenuSuperior);
        jpMenuSuperior.setLayout(jpMenuSuperiorLayout);
        jpMenuSuperiorLayout.setHorizontalGroup(
            jpMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuSuperiorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpMenuItemS1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jpMenuItemS2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jpMenuItemS3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jpMenuItemS4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpMenuItemS5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jpMenuSuperiorLayout.setVerticalGroup(
            jpMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpMenuItemS1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpMenuItemS2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpMenuItemS3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpMenuItemS4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpMenuItemS5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        escritorio.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jpLateral.setBackground(new java.awt.Color(23, 28, 46));

        jpLogo1.setBackground(new java.awt.Color(23, 28, 46));

        javax.swing.GroupLayout jpLogo1Layout = new javax.swing.GroupLayout(jpLogo1);
        jpLogo1.setLayout(jpLogo1Layout);
        jpLogo1Layout.setHorizontalGroup(
            jpLogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpLogo1Layout.setVerticalGroup(
            jpLogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        jpMenuLateral.setBackground(new java.awt.Color(23, 28, 46));

        jpMenuItemL1.setBackground(new java.awt.Color(33, 46, 67));
        jpMenuItemL1.setPreferredSize(new java.awt.Dimension(188, 55));

        jlGestorUsuarios.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlGestorUsuarios.setForeground(new java.awt.Color(193, 193, 193));
        jlGestorUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Recursos/img/gUsuarios.png"))); // NOI18N
        jlGestorUsuarios.setText("Gestor de Usuarios");
        jlGestorUsuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlGestorUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGestorUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemL1Layout = new javax.swing.GroupLayout(jpMenuItemL1);
        jpMenuItemL1.setLayout(jpMenuItemL1Layout);
        jpMenuItemL1Layout.setHorizontalGroup(
            jpMenuItemL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlGestorUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuItemL1Layout.setVerticalGroup(
            jpMenuItemL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuItemL1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlGestorUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpMenuItemL2.setBackground(new java.awt.Color(33, 46, 67));
        jpMenuItemL2.setPreferredSize(new java.awt.Dimension(188, 55));

        jlGestorLibros.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlGestorLibros.setForeground(new java.awt.Color(193, 193, 193));
        jlGestorLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Recursos/img/gLibros.png"))); // NOI18N
        jlGestorLibros.setText("Gestor de Libros        ");
        jlGestorLibros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlGestorLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGestorLibrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemL2Layout = new javax.swing.GroupLayout(jpMenuItemL2);
        jpMenuItemL2.setLayout(jpMenuItemL2Layout);
        jpMenuItemL2Layout.setHorizontalGroup(
            jpMenuItemL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlGestorLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuItemL2Layout.setVerticalGroup(
            jpMenuItemL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuItemL2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlGestorLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpMenuItemL3.setBackground(new java.awt.Color(33, 46, 67));
        jpMenuItemL3.setPreferredSize(new java.awt.Dimension(188, 55));

        jlGestorEjemplares.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlGestorEjemplares.setForeground(new java.awt.Color(193, 193, 193));
        jlGestorEjemplares.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlGestorEjemplares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Recursos/img/gEjemplares.png"))); // NOI18N
        jlGestorEjemplares.setText("Gestor de Ejemplares");
        jlGestorEjemplares.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlGestorEjemplares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGestorEjemplaresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemL3Layout = new javax.swing.GroupLayout(jpMenuItemL3);
        jpMenuItemL3.setLayout(jpMenuItemL3Layout);
        jpMenuItemL3Layout.setHorizontalGroup(
            jpMenuItemL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlGestorEjemplares, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );
        jpMenuItemL3Layout.setVerticalGroup(
            jpMenuItemL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuItemL3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlGestorEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpMenuItemL4.setBackground(new java.awt.Color(33, 46, 67));
        jpMenuItemL4.setPreferredSize(new java.awt.Dimension(188, 55));

        jlGestorPrestamos.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlGestorPrestamos.setForeground(new java.awt.Color(193, 193, 193));
        jlGestorPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlGestorPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Recursos/img/gPrestamos.png"))); // NOI18N
        jlGestorPrestamos.setText("Gestor de Prestamos");
        jlGestorPrestamos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlGestorPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGestorPrestamosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemL4Layout = new javax.swing.GroupLayout(jpMenuItemL4);
        jpMenuItemL4.setLayout(jpMenuItemL4Layout);
        jpMenuItemL4Layout.setHorizontalGroup(
            jpMenuItemL4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlGestorPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuItemL4Layout.setVerticalGroup(
            jpMenuItemL4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuItemL4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlGestorPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpMenuLateralLayout = new javax.swing.GroupLayout(jpMenuLateral);
        jpMenuLateral.setLayout(jpMenuLateralLayout);
        jpMenuLateralLayout.setHorizontalGroup(
            jpMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpMenuItemL1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jpMenuItemL2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jpMenuItemL3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jpMenuItemL4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jpMenuLateralLayout.setVerticalGroup(
            jpMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenuItemL1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpMenuItemL2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpMenuItemL3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpMenuItemL4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpLogo.setBackground(new java.awt.Color(23, 28, 46));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Recursos/img/logoBiblioteca.png"))); // NOI18N
        jlLogo.setText(" ");

        javax.swing.GroupLayout jpLogoLayout = new javax.swing.GroupLayout(jpLogo);
        jpLogo.setLayout(jpLogoLayout);
        jpLogoLayout.setHorizontalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpLogoLayout.setVerticalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpLateralLayout = new javax.swing.GroupLayout(jpLateral);
        jpLateral.setLayout(jpLateralLayout);
        jpLateralLayout.setHorizontalGroup(
            jpLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLateralLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpLogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpLateralLayout.setVerticalGroup(
            jpLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLateralLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(escritorio)
                    .addComponent(jpMenuSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(jpMenuSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        getContentPane().add(jpFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlGestorPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGestorPrestamosMouseClicked
        vistaGestorDePrestamos vgp = new vistaGestorDePrestamos();
        inicializarJInternalFrame(vgp, "Gestion de Prestamos");
    }//GEN-LAST:event_jlGestorPrestamosMouseClicked

    private void jlGestorEjemplaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGestorEjemplaresMouseClicked
        VistaGestorEjemplares gp = new VistaGestorEjemplares();
        inicializarJInternalFrame(gp, "Gestion de Ejemplares");
    }//GEN-LAST:event_jlGestorEjemplaresMouseClicked

    private void jlGestorLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGestorLibrosMouseClicked
        vistaGestorLibros gp = new vistaGestorLibros();
        inicializarJInternalFrame(gp, "Gestion de Libros");
    }//GEN-LAST:event_jlGestorLibrosMouseClicked

    private void jlGestorUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGestorUsuariosMouseClicked
        vistaGestorUsuarios usuarioVista = new vistaGestorUsuarios();
        inicializarJInternalFrame(usuarioVista, "Gestion de Usuarios");
    }//GEN-LAST:event_jlGestorUsuariosMouseClicked

    private void jlConsultas9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConsultas9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlConsultas9MouseClicked

    private void jlConsultas8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConsultas8MouseClicked
    vistaConsultaLectoresYLibrosXPrestamo usuarioVista = new vistaConsultaLectoresYLibrosXPrestamo();
    inicializarJInternalFrame(usuarioVista, "Gestion de Usuarios");
    }//GEN-LAST:event_jlConsultas8MouseClicked

    private void jlConsultas7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConsultas7MouseClicked
    VistaConsultarLibrosXAutor vla = new VistaConsultarLibrosXAutor();
        inicializarJInternalFrame(vla, "Consulta libros por autor");
    }//GEN-LAST:event_jlConsultas7MouseClicked

    private void jlConsultas6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConsultas6MouseClicked
    vistaConsultaLectoresConPrestamosVencidos vlcpv = new vistaConsultaLectoresConPrestamosVencidos();
        inicializarJInternalFrame(vlcpv, "Consulta de Prestamos");
    }//GEN-LAST:event_jlConsultas6MouseClicked

    private void jlConsultas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConsultas1MouseClicked
        vistaConsultarEjemplarLibro gp = new vistaConsultarEjemplarLibro();
        inicializarJInternalFrame(gp, "Consulta cantidad de ejemplares por libro");
    }//GEN-LAST:event_jlConsultas1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

//            UIManager.setLookAndFeel(new FlatLightLaf());
            FlatGradiantoDeepOceanIJTheme.setup();

        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jlConsultas1;
    private javax.swing.JLabel jlConsultas6;
    private javax.swing.JLabel jlConsultas7;
    private javax.swing.JLabel jlConsultas8;
    private javax.swing.JLabel jlConsultas9;
    private javax.swing.JLabel jlGestorEjemplares;
    private javax.swing.JLabel jlGestorLibros;
    private javax.swing.JLabel jlGestorPrestamos;
    private javax.swing.JLabel jlGestorUsuarios;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpLateral;
    private javax.swing.JPanel jpLogo;
    private javax.swing.JPanel jpLogo1;
    private javax.swing.JPanel jpMenuItemL1;
    private javax.swing.JPanel jpMenuItemL2;
    private javax.swing.JPanel jpMenuItemL3;
    private javax.swing.JPanel jpMenuItemL4;
    private javax.swing.JPanel jpMenuItemS1;
    private javax.swing.JPanel jpMenuItemS2;
    private javax.swing.JPanel jpMenuItemS3;
    private javax.swing.JPanel jpMenuItemS4;
    private javax.swing.JPanel jpMenuItemS5;
    private javax.swing.JPanel jpMenuLateral;
    private javax.swing.JPanel jpMenuSuperior;
    // End of variables declaration//GEN-END:variables
}
